import Link from "next/link";
import { useAuth } from "../context/AuthContext";

const FEATURES = [
  {
    icon: "🤖",
    gradient: "from-indigo-500 to-violet-500",
    title: "AI-powered explanations",
    description: "Stuck on a question? Get an instant, plain-English explanation generated by an AI tutor.",
  },
  {
    icon: "📊",
    gradient: "from-emerald-500 to-teal-500",
    title: "Domain-by-domain analytics",
    description: "See your accuracy across all 6 CTFL domains and spot exactly where to focus next.",
  },
  {
    icon: "🎯",
    gradient: "from-amber-500 to-rose-500",
    title: "Adaptive practice sessions",
    description: "Sessions are weighted toward your weakest domains, so every question you answer counts.",
  },
];

export default function HomePage() {
  const { user } = useAuth();

  return (
    <div className="bg-white">
      <section className="relative overflow-hidden bg-gradient-to-b from-sky-50 via-white to-white px-4 py-16 sm:py-24">
        <div className="pointer-events-none absolute -left-24 top-10 h-72 w-72 rounded-full bg-cyan-300/30 blur-3xl" />
        <div className="pointer-events-none absolute -right-16 top-40 h-72 w-72 rounded-full bg-violet-300/30 blur-3xl" />

        <div className="relative mx-auto grid max-w-5xl grid-cols-1 items-center gap-12 lg:grid-cols-2">
          <div>
            <span className="inline-block rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-indigo-700">
              AI-powered CTFL prep
            </span>
            <h1 className="mt-4 text-4xl font-bold leading-tight text-gray-900 sm:text-5xl">
              Master ISTQB CTFL with an{" "}
              <span className="bg-gradient-to-r from-indigo-600 via-violet-600 to-fuchsia-600 bg-clip-text text-transparent">
                AI tutor
              </span>{" "}
              by your side
            </h1>
            <p className="mt-4 max-w-md text-lg text-gray-600">
              Practice real exam-style questions, get instant AI explanations, and track your accuracy across
              every domain until you&apos;re ready to pass.
            </p>

            <div className="mt-8 flex flex-wrap gap-3">
              {user ? (
                <>
                  <Link
                    href="/practice"
                    className="rounded-md bg-gradient-to-r from-indigo-600 to-violet-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition-all hover:from-indigo-500 hover:to-violet-500 active:scale-[0.98]"
                  >
                    Continue practicing
                  </Link>
                  <Link
                    href="/dashboard"
                    className="rounded-md border border-gray-200 px-5 py-2.5 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50"
                  >
                    View analytics
                  </Link>
                </>
              ) : (
                <>
                  <Link
                    href="/register"
                    className="rounded-md bg-gradient-to-r from-indigo-600 to-violet-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition-all hover:from-indigo-500 hover:to-violet-500 active:scale-[0.98]"
                  >
                    Get started free
                  </Link>
                  <Link
                    href="/login"
                    className="rounded-md border border-gray-200 px-5 py-2.5 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50"
                  >
                    Log in
                  </Link>
                </>
              )}
            </div>

            <div className="mt-8 flex flex-wrap gap-2 text-xs font-medium text-gray-500">
              <span className="rounded-full bg-gray-100 px-3 py-1">6 CTFL domains</span>
              <span className="rounded-full bg-gray-100 px-3 py-1">Instant AI feedback</span>
              <span className="rounded-full bg-gray-100 px-3 py-1">Progress tracking</span>
            </div>
          </div>

          <div className="relative">
            <img
              src="/hero-illustration.webp"
              alt="An AI tutor robot handing code snippets to two students studying at laptops"
              className="w-full animate-float rounded-3xl shadow-xl"
            />
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-4 py-16">
        <h2 className="text-center text-2xl font-semibold text-gray-900">Everything you need to pass</h2>
        <div className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-3">
          {FEATURES.map((feature) => (
            <div
              key={feature.title}
              className="rounded-xl border border-gray-100 bg-white p-6 shadow transition-all hover:-translate-y-1 hover:shadow-lg"
            >
              <span
                className={`flex h-11 w-11 items-center justify-center rounded-full bg-gradient-to-br text-lg ${feature.gradient}`}
              >
                {feature.icon}
              </span>
              <h3 className="mt-4 font-semibold text-gray-900">{feature.title}</h3>
              <p className="mt-1 text-sm text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {!user && (
        <section className="mx-4 mb-16 max-w-5xl rounded-2xl bg-gradient-to-r from-indigo-600 via-violet-600 to-fuchsia-600 px-8 py-10 text-center shadow-xl sm:mx-auto">
          <h2 className="text-2xl font-semibold text-white">Ready to ace your CTFL exam?</h2>
          <p className="mt-2 text-indigo-100">Create a free account and start practicing in under a minute.</p>
          <Link
            href="/register"
            className="mt-6 inline-block rounded-md bg-white px-5 py-2.5 text-sm font-semibold text-indigo-700 shadow-sm transition-all hover:bg-indigo-50 active:scale-[0.98]"
          >
            Get started free
          </Link>
        </section>
      )}
    </div>
  );
}
