# Generated by Django 6.0.7 on 2026-08-27 07:13

from django.db import migrations, models


def verify_existing_users(apps, schema_editor):
    """Accounts that already existed before email verification was
    introduced keep working -- only new registrations must verify."""
    User = apps.get_model("accounts", "User")
    User.objects.update(email_verified=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(verify_existing_users, noop),
    ]
