# Generated by Django 6.0.7 on 2026-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiexplanation',
            name='generated_by_model',
            field=models.CharField(default='llama-3.3-70b-versatile', max_length=50),
        ),
    ]
