# Generated by Django 6.0.7 on 2026-08-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanations', '0002_alter_aiexplanation_generated_by_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiexplanation',
            name='generated_by_model',
            field=models.CharField(default='openai/gpt-oss-20b', max_length=50),
        ),
    ]
