# Generated by Django 6.0.7 on 2026-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanations', '0003_alter_aiexplanation_generated_by_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexplanation',
            name='context_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
