# Generated by Django 6.0.7 on 2026-08-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_normalize_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='domain_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
