# Generated by Django 6.0.7 on 2026-08-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_generationjob_domain_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('test', 'Test')], default='practice', max_length=10),
        ),
        migrations.CreateModel(
            name='DomainResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='questions.domain')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
