# Generated by Django 6.0.7 on 2026-08-27 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_topic_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
