# Generated by Django 6.0.7 on 2026-09-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_attempt_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('test', 'Test'), ('mock', 'ISTQB Mock Test')], default='practice', max_length=10),
        ),
    ]
