# Generated by Django 6.0.7 on 2026-09-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
